[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[env]
  [env.production]
    VITE_GOOGLE_SHEETS_ID = ""
    VITE_GOOGLE_SHEETS_API_KEY = ""
    VITE_WHATSAPP_TOKEN = ""

[context.production.environment]
  VITE_GOOGLE_SHEETS_ID = ""
  VITE_GOOGLE_SHEETS_API_KEY = ""
  VITE_WHATSAPP_TOKEN = ""
